/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tfg2018.gui.views;

import com.tfg2018.gui.ApiManager.PostOperation;
import com.tfg2018.gui.RequestObjects.CreateTokenStructure;
import com.tfg2018.gui.RequestObjects.InstantTransactionStructure;
import com.tfg2018.gui.ResponseObject.KeyPair;
import com.tfg2018.gui.ResponseObject.Token;
import com.tfg2018.gui.factura.ComprobanteInfo;
import com.tfg2018.gui.factura.Factura;
import com.tfg2018.gui.factura.Participant;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tomas
 */
public class InvoiceDataShow extends javax.swing.JFrame {

    private Factura invoice;
    private String userName;
    private KeyPair userKeyPair;

    /**
     * Creates new form InvoiceDataShow
     */
    public InvoiceDataShow() {
        initComponents();
    }

    public InvoiceDataShow(String userName, KeyPair userKeyPair, Factura invoice) {
        initComponents();
        Participant emisor = invoice.getEmisor();
        Participant receptor = invoice.getReceptor();
        this.invoice = invoice;
        this.userName = userName;
        this.userKeyPair = userKeyPair;
        userNameLabel.setText(userName);
        String invoiceInfo = "*****************************EMISOR*****************************\n";
        invoiceInfo += invoiceParticipant(invoice, emisor);
        invoiceInfo += "\n****************************RECEPTOR****************************\n";
        invoiceInfo += invoiceParticipant(invoice, receptor);
        invoiceInfo += "\n****************************CONCEPTO****************************\n";
        invoiceInfo += invoiceConcept(invoice);
        invoiceInfo += "\n*****************************TASAS******************************\n";
        invoiceInfo += invoiceTasas(invoice);
        invoiceInfo += "\n*****************************INFO*******************************\n";
        invoiceInfo += invoiceInfo(invoice, invoice.getComprobante());
        this.invoiceInfoTextArea.setText(invoiceInfo);
    }

    public String invoiceTasas(Factura invoice) {
        String result = "";
        String aux[] = invoice.getImpuesto();
        for (int i = 0; i < aux.length; i++) {
            result += "impuesto " + (i + 1) + " --> " + aux[i] + '\n';
        }
        return result;
    }

    public String invoiceConcept(Factura invoice) {
        String result = "";
        String aux[] = invoice.getConcept();
        for (int i = 0; i < aux.length; i++) {
            result += "concepto " + (i + 1) + " --> " + aux[i] + '\n';
        }
        return result;
    }

    public String invoiceParticipant(Factura invoice, Participant participant) {
        String result = "";
        result += "Nombre --> " + participant.getNombre() + '\n';
        result += "Rfc --> " + participant.getRfc() + '\n';
        result += "País --> " + participant.getLocalizacion().getPaisEmisor() + '\n';
        result += "Estado --> " + participant.getLocalizacion().getEstadoEmisor() + '\n';
        result += "Municipio --> " + participant.getLocalizacion().getMunicipioEmisor() + '\n';
        result += "Código Postal --> " + participant.getLocalizacion().getCPEmisor() + '\n';
        result += "Calle --> " + participant.getLocalizacion().getCalleEmisor() + '\n';
        return result;
    }

    public String invoiceInfo(Factura invoice, ComprobanteInfo comprobante) {
        String result = "";
        result += "Fecha de expedición --> " + comprobante.getFecha() + '\n';
        result += "Forma de pago --> " + comprobante.getFormaDePago() + '\n';
        result += "Lugar de expedición --> " + comprobante.getLugarExpedicion() + '\n';
        result += "Método de pago --> " + comprobante.getMetodoDePago() + '\n';
        result += "Subtotal --> " + comprobante.getSubTotal() + '\n';
        result += "Total --> " + comprobante.getTotal() + '\n';
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JLabel();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceInfoTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(177, 212, 229));

        jPanel2.setBackground(new java.awt.Color(18, 57, 98));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de factura");

        jPanel9.setBackground(new java.awt.Color(121, 158, 178));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        userNameLabel.setBackground(new java.awt.Color(121, 158, 178));
        userNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tomas\\Pictures\\usuario.png")); // NOI18N
        userNameLabel.setText("Bonny SA");

        logOutButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tomas\\Pictures\\logout.png")); // NOI18N
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(logOutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userNameLabel)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(191, 191, 191)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        acceptButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        acceptButton.setText("Registrar Factura");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(121, 158, 178));

        invoiceInfoTextArea.setEditable(false);
        invoiceInfoTextArea.setColumns(20);
        invoiceInfoTextArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        invoiceInfoTextArea.setRows(5);
        invoiceInfoTextArea.setText("Estado --> MEXICO, D.F.\nMunicipio --> BENITO JUAREZ\nCódigo Postal --> 03240\nCalle --> AV. RIO MIXCOAC\n\n****************************RECEPTOR****************************\nNombre --> JUAN PEREZ PEREZ\nRfc --> PEPJ8001019Q8\nPaís --> Mexico\nEstado --> DISTRITO FEDERAL\nMunicipio --> COYOACAN\nCódigo Postal --> 04365\nCalle --> AV UNIVERSIDAD\n\n****************************CONCEPTO****************************\nconcepto 1 -->  unidad-> CAPSULAS, importe-> 244.00, cantidad-> 1.0, descripcion-> VIBRAMICINA 100MG 10, valorUnitario-> 244.00\nconcepto 2 -->  unidad-> BOTELLA, importe-> 137.93, cantidad-> 1.0, descripcion-> CLORUTO 500M, valorUnitario-> 137.93\nconcepto 3 -->  unidad-> TABLETAS, importe-> 84.50, cantidad-> 1.0, descripcion-> SEDEPRON 250MG 10, valorUnitario-> 84.50\n\n*****************************TASAS******************************\nimpuesto 1 --> tasa-> 0.00, importe-> 0.00, impuesto-> IVA\nimpuesto 2 --> tasa-> 16.00, importe-> 22.07, impuesto-> IVA\n\n*****************************INFO*******************************\nFecha de expedición --> 2012-01-01T20:38:12\nForma de pago --> PAGO EN UNA SOLA EXHIBICION\nLugar de expedición --> Mexico\nMétodo de pago --> cheque\nSubtotal --> 488.50\nTotal --> 488.50\n");
        jScrollPane1.setViewportView(invoiceInfoTextArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(acceptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(acceptButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        String respuesta = JOptionPane.showInputDialog(null, "Por favor escriba la dirección del beneficiario de la factura.", "Dirección del beneficiario", JOptionPane.QUESTION_MESSAGE);
        if (respuesta == null) {
            System.out.println("The user canceled");
        } else {
          PostOperation post = new PostOperation();
          KeyPair receiver = new KeyPair(respuesta);
            try {
                post.validateAddress(receiver);
                CreateTokenStructure tokenStructure = new CreateTokenStructure(this.userKeyPair.getAddress(), invoice.getTokenParameters());
                Token createdToken = post.generateToken(tokenStructure);
                InstantTransactionStructure transaction = new InstantTransactionStructure(this.userKeyPair.getAddress(), this.userKeyPair.getPrivkey(), respuesta, createdToken.getName());
                String responseId = post.createInstantTransaction(transaction);
                int confirmation = JOptionPane.showConfirmDialog(null, "factura registrada con éxito");
                Home homeFrame = new Home(this.userName, this.userKeyPair);
                InvoiceDataShow invoiceDataFrame = new InvoiceDataShow();
                invoiceDataFrame.setVisible(false);
                homeFrame.setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error durante la ejecución de su solicitud", "ERROR", JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(InvoiceDataShow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Home homeFrame = new Home(this.userName, this.userKeyPair);
        InvoiceDataShow dataFrame = new InvoiceDataShow();
        dataFrame.setVisible(false);
        homeFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        Log logFrame = new Log();
        Home homeFrame = new Home();
        logFrame.setVisible(true);
        homeFrame.setVisible(false);
        dispose();
    }//GEN-LAST:event_logOutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceDataShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceDataShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceDataShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceDataShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceDataShow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea invoiceInfoTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logOutButton;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
